spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdf
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: system
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
