server:
  port: 8095
  
spring:
  application:
    name: CONFIG-SERVER
    
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sachinghatage/microservice-with-durgesh-config
          clone-on-start: true